name: Build & Publish Image

on:
  push:
    tags:
      - 'v*'

jobs:
  Build_and_Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tagged version.
        id: ver
        run: echo ::set-output name=ver::${GITHUB_REF/refs\/tags\//}
      - name: Setup Docker Buildx.
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry.
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image & upload.
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/esp-idf:${{ steps.ver.outputs.ver }}
